=== xml-blockweek-project-FS17/alperlebnis/data/activitydb_schema.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="activities">
        <xs:complexType>
            <xs:sequence minOccurs="0" maxOccurs="unbounded">
                <xs:element ref="user"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="user">
        <xs:complexType>
            <xs:sequence minOccurs="0" maxOccurs="unbounded">
                <xs:element ref="activity"/>
            </xs:sequence>
            <xs:attribute name="name" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="activity">
        <xs:complexType>
            <xs:sequence>  
                <xs:element name="title" type="xs:string"/>
                <xs:element name="provider" type="xs:string"/>
                <xs:element name="activitydate" type="xs:date"/>
                <xs:element name="description" type="xs:string"/>
                <xs:element name="image" type="xs:anyURI"/>
                <xs:element ref="contact" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element name="price" type="activityprice"/>
                <xs:element name="signupstart" type="xs:date"/>
                <xs:element name="signupend" type="xs:date"/>
            </xs:sequence>
            <xs:attribute name="ID" type="xs:positiveInteger"/>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="contact">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="phone" type="xs:string"/>
                <xs:element name="email" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>    
    </xs:element>
    
    <!--Definition of more specific datatypes -->
    <xs:complexType name="activityprice">
        <xs:simpleContent>
          <xs:extension base="xs:float">
            <xs:attribute name="currency" type="currency" />
          </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    
    <xs:simpleType name="currency">
        <xs:restriction base="xs:string">
            <xs:enumeration value="CHF"/>
            <xs:enumeration value="EUR"/>
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== xml-blockweek-project-FS17/alperlebnis/data/activitydb.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="../pages/FO/eventflyers.xsl"?>
<activities xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="activitydb_schema.xsd" nextActivityId="5">
    <user name="bauer">
        <activity ID="1">
            <title>Stallbesichtigung</title>
            <provider>Bauern Verein HSLU</provider>
            <activitydate>2017-09-20</activitydate>
            <description>
                Die heile Bergwelt bei einem Schweizer Bergbauern erleben und selbst Hand anlegen.
            </description>
            <image>http://staufer.at/wp-content/uploads/2013/09/Stall-2.jpg</image>
            <contact>
                <phone>+41 41 777 77 77</phone>
                <email>bauern.verein@hslu.ch</email>
            </contact>
            <price currency="CHF">200.00</price>
            <signupstart>2017-09-10</signupstart>
            <signupend>2017-09-10</signupend>
        </activity>
		<activity ID="2">
            <title>Goldwaschen</title>
            <provider>Napf Gold Erlebnis</provider>
            <activitydate>2017-10-05</activitydate>
            <description>
                Gold waschen wie im wilden Westen
            </description>
            <image>../data/pictures/gold_wash.jpg</image>
            <contact>
                <phone>+41 41 777 77 77</phone>
                <email>gold.napf@hslu.ch</email>
            </contact>
            <price currency="CHF">80.00</price>
            <signupstart>2017-09-10</signupstart>
            <signupend>2017-09-10</signupend>
        </activity>
        <activity ID="3"><title>Wildwasser im Bergfluss</title><provider>Raftingverband HSLU</provider><activitydate>2017-03-14</activitydate><description>Jetzt das Rafting geniessen</description><image>http://www.3glav.com/wp-content/uploads/2016/01/soca-rafting-slovenia-bovec.jpg</image><contact><phone>079 614 91 19</phone><email>marc.nussbaumer@stud.hslu.ch</email></contact><price currency="CHF">500</price><signupstart>2017-03-13</signupstart><signupend>2017-03-14</signupend></activity><activity ID="4"><title>Wildwasser im Bergfluss</title><provider>Raftingverband HSLU</provider><activitydate>2017-03-14</activitydate><description>Jetzt das Rafting geniessen</description><image>http://www.3glav.com/wp-content/uploads/2016/01/soca-rafting-slovenia-bovec.jpg</image><contact><phone>079 614 91 19</phone><email>marc.nussbaumer@stud.hslu.ch</email></contact><price currency="CHF">500</price><signupstart>2017-03-13</signupstart><signupend>2017-03-14</signupend></activity></user>
</activities>
