=== xml-blockweek-project-FS17/alperlebnis/data/roomdb_schema.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="hostelrooms">
        <xs:complexType>
            <xs:sequence minOccurs="0" maxOccurs="unbounded">
                <xs:element ref="room"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="room">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="price" type="roomprice"/>
                <xs:element name="beds" type="xs:positiveInteger" />
                <xs:element name="image" type="xs:string"/>
                <xs:element name="description" type="xs:string" />
                <xs:element name="bookings">
                    <xs:complexType>
                        <xs:sequence minOccurs="0" maxOccurs="unbounded">
                                <xs:element ref="booking"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
               
            </xs:sequence>
            <xs:attribute name="name" type="xs:string"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="booking">
        <xs:complexType>
            <xs:sequence>
                <!-- Date is used to compare dates with xpath, this would not 
                be supported with the european format -->
                <xs:element name="startdate" type="xs:date"/>
                <xs:element name="enddate" type="xs:date"/>
                <xs:element name="email" type="xs:string"/>
                <xs:element name="paidprice" type="xs:float"/>
                <xs:element ref="bookingaddress"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="bookingaddress">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="salutation" type="xs:string"/>
                <xs:element name="firstname" type="xs:string"/>
                <xs:element name="lastname" type="xs:string"/>
                <xs:element name="address" type="xs:string"/>
                <xs:element name="zipcode" type="xs:positiveInteger"/>
                <xs:element name="state" type="xs:string"/>
                <xs:element name="country" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <!--Definition of more specific datatypes -->
    <xs:complexType name="roomprice">
        <xs:simpleContent>
          <xs:extension base="xs:float">
            <xs:attribute name="currency" type="currency" />
          </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    
    <xs:simpleType name="currency">
        <xs:restriction base="xs:string">
            <xs:enumeration value="CHF"/>
            <xs:enumeration value="EUR"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== xml-blockweek-project-FS17/alperlebnis/data/roomdb.xml
<hostelrooms xsi:noNamespaceSchemaLocation="roomdb_schema.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <room name='Edelweiss'>
        <price currency="CHF">100.00</price>
        <beds>2</beds>
        <image>../data/pictures/edelweiss-room.jpg</image>
        <description>
            Gemütliches helles Zimmer. Hier vergisst man schnell die Mühen des Tages.
        </description>
        <bookings>
            <booking>
                <!--Use of xml-date to ensure that it is comparable in XPATH -->
                <startdate>2017-09-24</startdate>
                <enddate>2017-09-27</enddate>
                <email>marc.nussbaumer@stud.hslu.ch</email>
                <paidprice>250.00</paidprice>
                <bookingaddress>
                    <salutation>Herr</salutation>
                    <firstname>Marc</firstname>
                    <lastname>Nussbaumer</lastname>
                    <address>Hochrütiring 10</address>
                    <zipcode>6005</zipcode>
                    <state>Luzern</state>
                    <country>Schweiz</country>
                </bookingaddress>
            </booking>
            <booking>
                <!--Use of xml-date to ensure that it is comparable in XPATH -->
                <startdate>2017-09-28</startdate>
                <enddate>2017-09-29</enddate>
                <email>max@muster.ch</email>
                <paidprice>200.00</paidprice>
                <bookingaddress>
                    <salutation>Herr</salutation>
                    <firstname>Max</firstname>
                    <lastname>Muster</lastname>
                    <address>Musterstrasse 10</address>
                    <zipcode>6005</zipcode>
                    <state>Luzern</state>
                    <country>Schweiz</country>
                </bookingaddress>
            </booking>
        </bookings>
    </room>
    <room name='Enzian'>
        <price currency="CHF">100.00</price>
        <beds>2</beds>
        <image>../data/pictures/enzian-room.jpg</image>
        <description>
            Stilvoll eingerichtetes Zimmer. Hier werden Sie schlafen wie im siebten Himmel.
        </description>
        <bookings></bookings>
    </room>
    <room name='Alperose'>
        <price currency="CHF">200.00</price>
        <beds>4</beds>
        <image>../data/pictures/Alpenrose-room.jpg</image>
        <description>
            Praktisches Familienzimmer mit Elternbett und einem Etagenbett für die Kinder.
        </description>
        <bookings></bookings>
    </room>
    <room name='Krokus'>
        <price currency="CHF">400.00</price>
        <beds>10</beds>
        <image>../data/pictures/Krokus-room.jpg</image>
        <description>
            Massenschlag mit praktischer Raumaufteilung für Gruppen bis zu 10 Personen.
        </description>
        <bookings></bookings>
    </room>
    <room name='Glockenblume'>
        <price currency="CHF">150.00</price>
        <beds>1</beds>
        <image>../data/pictures/Glockenblume-room.jpg</image>
        <description>
            In warmen Farbtönen eingerichtetes Einzelzimmer.
        </description>
        <bookings></bookings>
    </room>
</hostelrooms>
